############################# English ############################
[en]
languageName = "En"
title = "Stichting Algorithm Audit Foundation"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_content = "Stichting Algorithm Audit ..."