############################# English ############################
[en]
languageName = "En"
title = "Algorithm Audit"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_content = "Stichting Algorithm Audit is a nonprofit organization registred under license number 83979212 at the Dutch Chambre of Commerce."