# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Kennisplatform"
weight = 2
hasChildren = true
url = "/nl/knowledge-platform"
  [[main]]
  parent = "Kennisplatform"
  name = "Kennisbank"
  url = "/nl/knowledge-platform/knowledge-base"
  weight = 1
  [[main.params]]
    icon = "fa-brain"
  [[main]]
  parent = "Kennisplatform"
  name = "AI-verordening standaarden"
  url = "/nl/knowledge-platform/standards"
  weight = 2
  [[main.params]]
    icon = "fa-check"
  [[main]]
  parent = "Kennisplatform"
  name = "AI beleidsobservatorium"
  url = "/nl/knowledge-platform/policy-observatory"
  weight = 3
  [[main.params]]
    icon = "fa-binoculars"
  [[main]]
  parent = "Kennisplatform"
  name = "Projectwerk"
  url = "/nl/knowledge-platform/project-work"
  weight = 4
  [[main.params]]
    icon = "fa-hands-helping"
  [[main]]
  identifier = "knowledge_platform_overview"
  parent = "Kennisplatform"
  name = "Overzicht"
  url = "/nl/knowledge-platform/"
  weight = 5
  [[main.params]]
    featured = true

[[main]]
name = "Algoprudentie"
weight = 3
url = "/algoprudence"
hasChildren = true
  [[main]]
  parent = "Algoprudentie"
  name = "Casuïstiek"
  url = "/nl/algoprudence/case-repository"
  weight = 1
  [[main.params]]
    icon = "fa-database"
  [[main]]
  parent = "Algoprudentie"
  name = "Dien een case in"
  url = "/nl/algoprudence/submit-a-case"
  weight = 2
  [[main.params]]
    icon = "fa-arrow-right"
  [[main]]
  parent = "Algoprudentie"
  name = "Werkwijze"
  url = "/nl/algoprudence/how-we-work"
  weight = 3
  [[main.params]]
    icon = "fa-question"
  [[main]]
  identifier = "algoprudence_overview"
  parent = "Algoprudentie"
  name = "Overzicht"
  url = "/nl/algoprudence/"
  weight = 4
  [[main.params]]
    featured = true

[[main]]
name = "Technische tools"
weight = 4
hasChildren = true
url = "/nl/technical-tools"
  [[main]]
  parent = "Technische tools"
  name = "Unsupervised bias detectie tool"
  url = "/nl/technical-tools/BDT"
  weight = 1
  [[main.params]]
    icon = "fa-search-plus"
  [[main]]
  parent = "Technische tools"
  name = "Synthetische data generatie tool"
  url = "/nl/technical-tools/SDG"
  weight = 2
  [[main.params]]
    icon = "fa-table"
  [[main]]
  parent = "Technische tools"
  name = "AI-verordening implementatie tool"
  url = "/nl/technical-tools/implementation-tool"
  weight = 3
  [[main.params]]
    icon = "fa-file"
  [[main]]
  identifier = "technical_tools_overview"
  parent = "Technische tools"
  name = "Overzicht"
  url = "/nl/technical-tools/"
  weight = 4
  [[main.params]]
    featured = true



[[main]]
name = "Evenementen"
url = "events"
weight = 5
hasChildren = true
  [[main]]
  parent = "Evenementen"
  name = "Activiteiten"
  url = "/nl/events/activities"
  weight = 1
  [[main.params]]
    icon = "fa-calendar"
  [[main]]
  parent = "Evenementen"
  name = "Persberichten"
  url = "/nl/events/press_room"
  weight = 2
  [[main.params]]
    icon = "fa-newspaper"

[[main]]
name = "Over ons"
weight = 6
hasChildren = true
  [[main]]
    featured = true
  [[main]]
  parent = "Over ons"
  name = "FAQ"
  url = "/nl/about/faq"
  weight = 1
  [[main.params]]
    icon = "fa-question"
  [[main]]
  parent = "Over ons"
  name = "Teams"
  url = "/nl/about/teams"
  weight = 2
  [[main.params]]
    icon = "fa-users"
  [[main]]
  parent = "Over ons"
  name = "Bestuur"
  url = "/nl/about/boards"
  weight = 3
  [[main.params]]
    icon = "fa-user-friends"
  [[main]]
  parent = "Over ons"
  name = "Vacatures"
  url = "/nl/about/vacancies"
  weight = 4
  [[main.params]]
    icon = "fa-user-check"
  [[main]]
  parent = "Over ons"
  name = "Kom in contact"
  url = "/nl/about/contact"
  weight = 5
  [[main.params]]
    featured = true