# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Cases"
url = "cases"
weight = 2

[[main]]
name = "Partners and publications"
url = "partnersandpublications"
weight = 3

[[main]]
name = "Knowledge base"
url = "knowledgebase"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

[[main]]
name = "About"
url = "faq"
weight = 6