# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Algoprudence"
url = "algoprudence"
weight = 2
hasChildren = true
  [[main]]
  parent = "Algoprudence"
  name = "Dropdown Item 1"
  url = "algoprudence"
  weight = 1
  [[main]]
  parent = "Algoprudence"
  name = "Dropdown Item 2"
  url = "algoprudence"
  weight = 1
  [[main]]
  parent = "Algoprudence"
  name = "Dropdown Item 3"
  url = "algoprudence"
  weight = 1

[[main]]
name = "Bias scan"
url = "bias_scan"
weight = 3

[[main]]
name = "Knowledge base"
url = "knowledge_base"
weight = 4

[[main]]
name = "Events"
url = "events"
weight = 5

[[main]]
name = "FAQ"
url = "faq"
weight = 6

[[main]]
name = "About"
url = "about"
weight = 7

