# main menu
[[main]]
name = "Algoprudence"
weight = 2
url = "/algoprudence"
hasChildren = true
  [[main]]
  parent = "Algoprudence"
  name = "Submit a case"
  url = "algoprudence/submit-a-case"
  weight = 1
  [[main.params]]
    featured = true
  [[main]]
  parent = "Algoprudence"
  name = "Cases"
  url = "/algoprudence"
  weight = 2
  [[main.params]]
    icon = "fa-database"
  [[main]]
  parent = "Algoprudence"
  name = "How we work"
  url = "/algoprudence/how-we-work"
  weight = 3
  [[main.params]]
    icon = "fa-question"

[[main]]
name = "Technical tools"
weight = 3
hasChildren = true
url = "/technical-tools/BDT"
  [[main]]
  parent = "Technical tools"
  name = "Github code"
  url = "https://github.com/NGO-Algorithm-Audit/"
  weight = 1
  [[main.params]]
    featured = true
    target = "_blank"
  [[main]]
  parent = "Technical tools"
  name = "Bias detection tool"
  url = "/technical-tools/BDT"
  weight = 2
  [[main.params]]
    icon = "fa-search"
    subtitle = "Open source AI auditing tools"
  [[main]]
  parent = "Technical tools"
  name = "Synthetic data generation"
  url = "/technical-tools/SDG"
  weight = 3
  [[main.params]]
    icon = "fa-table"
  [[main]]
  parent = "Technical tools"
  name = "AI Act Implementation Tool"
  url = "/technical-tools/implementation-tool"
  weight = 4
  [[main.params]]
    icon = "fa-file"

[[main]]
name = "Knowledge platform"
weight = 1
hasChildren = true
url = "/knowledge-platform/knowledge-base"
  [[main]]
  parent = "Knowledge platform"
  name = "AI Act standards"
  url = "/knowledge-platform/standards"
  weight = 1
  [[main.params]]
    icon = "fa-check"
  [[main]]
  parent = "Knowledge platform"
  name = "AI policy observatory"
  url = "/knowledge-platform/policy-observatory"
  weight = 2
  [[main.params]]
    icon = "fa-binoculars"
  [[main]]
  parent = "Knowledge platform"
  name = "Knowledge base"
  url = "/knowledge-platform/knowledge-base"
  weight = 3
  [[main.params]]
    icon = "fa-brain"
  [[main]]
  parent = "Knowledge platform"
  name = "Project work"
  url = "/knowledge-platform/project-work"
  weight = 4
  [[main.params]]
    icon = "fa-hands-helping"

[[main]]
name = "Events"
url = "events"
weight = 4
hasChildren = true
  [[main]]
  parent = "Events"
  name = "Activities"
  url = "/events/activities"
  weight = 1
  [[main.params]]
    icon = "fa-calendar"
  [[main]]
  parent = "Events"
  name = "Press room"
  url = "/events/press_room"
  weight = 2
  [[main.params]]
    icon = "fa-newspaper"

[[main]]
name = "About"
weight = 5
hasChildren = true
url = "/about/contact"
  [[main]]
  parent = "About"
  name = "Get in touch"
  url = "/about/contact"
  weight = 1
  [[main.params]]
    featured = true
  [[main]]
  parent = "About"
  name = "FAQ"
  url = "/about/faq"
  weight = 2
  [[main.params]]
    icon = "fa-question"
  [[main]]
  parent = "About"
  name = "Teams"
  url = "/about/teams"
  weight = 3
  [[main.params]]
    icon = "fa-users"
  [[main]]
  parent = "About"
  name = "Boards"
  url = "/about/boards"
  weight = 4
  [[main.params]]
    icon = "fa-user-friends"
  [[main]]
  parent = "About"
  name = "Vacancies"
  url = "/about/vacancies"
  weight = 5
  [[main.params]]
    icon = "fa-user-check"