# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Algoprudence"
weight = 2
hasChildren = true
  [[main]]
  parent = "Algoprudence"
  name = "Submit a case for review"
  url = "/submit-case"
  weight = 1
  [[main.params]]
    featured = true
  [[main]]
  parent = "Algoprudence"
  name = "Cases"
  url = "/algoprudence"
  weight = 2
  [[main.params]]
    icon = "fa-database"
  [[main]]
  parent = "Algoprudence"
  name = "How we work"
  url = "/how-we-work"
  weight = 3
  [[main.params]]
    icon = "fa-question"

[[main]]
name = "Technical Tools"
weight = 3
hasChildren = true
  [[main]]
  parent = "Technical Tools"
  name = "Bias detection tool"
  url = "/bias_scan"
  weight = 1
  [[main.params]]
    icon = "fa-toolbox"
  [[main]]
  parent = "Technical Tools"
  name = "Synthetic data generation"
  url = "/bias_scan"
  weight = 2
  [[main.params]]
    icon = "fa-table"

[[main]]
name = "Knowledge base"
url = "knowledge_base"
weight = 4

[[main]]
name = "Events"
url = "events"
weight = 5

[[main]]
name = "FAQ"
url = "faq"
weight = 6

[[main]]
name = "About"
url = "about"
weight = 7

