# main menu
[[main]]
name = "Home"
url = "nl/"
weight = 1

[[main]]
name = "Algoprudentie"
url = "nl/algoprudence"
weight = 2

[[main]]
name = "Bias scan"
url = "nl/bias_scan"
weight = 3

[[main]]
name = "Kennisbank"
url = "nl/knowledge_base"
weight = 4

[[main]]
name = "Events"
url = "nl/events"
weight = 5

[[main]]
name = "FAQ"
url = "nl/faq"
weight = 6

[[main]]
name = "Over AA"
url = "nl/about"
weight = 7

