# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Knowledge platform"
weight = 2
hasChildren = true
url = "/knowledge-platform"
  [[main]]
  parent = "Knowledge platform"
  name = "Knowledge base"
  url = "/knowledge-platform/knowledge-base"
  weight = 1
  [[main.params]]
    icon = "fa-brain"
  [[main]]
  parent = "Knowledge platform"
  name = "AI Act standards"
  url = "/knowledge-platform/standards"
  weight = 2
  [[main.params]]
    icon = "fa-check"
  [[main]]
  parent = "Knowledge platform"
  name = "AI policy observatory"
  url = "/knowledge-platform/policy-observatory"
  weight = 3
  [[main.params]]
    icon = "fa-binoculars"
  [[main]]
  parent = "Knowledge platform"
  name = "Project work"
  url = "/knowledge-platform/project-work"
  weight = 4
  [[main.params]]
    icon = "fa-hands-helping"
  [[main]]
  identifier = "knowledge_platform_overview"
  parent = "Knowledge platform"
  name = "Overview"
  url = "/knowledge-platform/"
  weight = 5
  [[main.params]]
    featured = true

[[main]]
name = "Algoprudence"
weight = 3
url = "/algoprudence"
hasChildren = true
  [[main]]
  parent = "Algoprudence"
  name = "Case repository"
  url = "/algoprudence/case-repository"
  weight = 1
  [[main.params]]
    icon = "fa-database"
  [[main]]
  parent = "Algoprudence"
  name = "Submit a case"
  url = "algoprudence/submit-a-case"
  weight = 2
  [[main.params]]
    icon = "fa-arrow-right"
  [[main]]
  parent = "Algoprudence"
  name = "How we work"
  url = "/algoprudence/how-we-work"
  weight = 3
  [[main.params]]
    icon = "fa-question"
  [[main]]
  identifier = "algoprudence_overview"
  parent = "Algoprudence"
  name = "Overview"
  url = "/algoprudence/"
  weight = 4
  [[main.params]]
    featured = true

[[main]]
name = "Technical tools"
weight = 4
hasChildren = true
url = "/technical-tools"
  [[main]]
  parent = "Technical tools"
  name = "Unsupervised bias detection tool"
  url = "/technical-tools/BDT"
  weight = 1
  [[main.params]]
    icon = "fa-search-plus"
  [[main]]
  parent = "Technical tools"
  name = "Synthetic data generation tool"
  url = "/technical-tools/SDG"
  weight = 2
  [[main.params]]
    icon = "fa-table"
  [[main]]
  parent = "Technical tools"
  name = "AI Act implementation tool"
  url = "/technical-tools/implementation-tool"
  weight = 3
  [[main.params]]
    icon = "fa-file"
  [[main]]
  identifier = "technical_tools_overview"
  parent = "Technical tools"
  name = "Overview"
  url = "/technical-tools/"
  weight = 4
  [[main.params]]
    featured = true



[[main]]
name = "Events"
url = "events"
weight = 5
hasChildren = true
  [[main]]
  parent = "Events"
  name = "Activities"
  url = "/events/activities"
  weight = 1
  [[main.params]]
    icon = "fa-calendar"
  [[main]]
  parent = "Events"
  name = "Press room"
  url = "/events/press_room"
  weight = 2
  [[main.params]]
    icon = "fa-newspaper"

[[main]]
name = "About"
weight = 6
hasChildren = true
url = "/about/contact"
  [[main]]
  parent = "About"
  name = "Get in touch"
  url = "/about/contact"
  weight = 1
  [[main.params]]
    featured = true
  [[main]]
  parent = "About"
  name = "FAQ"
  url = "/about/faq"
  weight = 2
  [[main.params]]
    icon = "fa-question"
  [[main]]
  parent = "About"
  name = "Teams"
  url = "/about/teams"
  weight = 3
  [[main.params]]
    icon = "fa-users"
  [[main]]
  parent = "About"
  name = "Boards"
  url = "/about/boards"
  weight = 4
  [[main.params]]
    icon = "fa-user-friends"
  [[main]]
  parent = "About"
  name = "Vacancies"
  url = "/about/vacancies"
  weight = 5
  [[main.params]]
    icon = "fa-user-check"