# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Algoprudence"
weight = 2
hasChildren = true
  [[main]]
  parent = "Algoprudence"
  name = "Submit a case for review"
  url = "algoprudence/submit-a-case"
  weight = 1
  [[main.params]]
    featured = true
  [[main]]
  parent = "Algoprudence"
  name = "Cases"
  url = "/algoprudence"
  weight = 2
  [[main.params]]
    icon = "fa-database"
  [[main]]
  parent = "Algoprudence"
  name = "How we work"
  url = "/algoprudence/how-we-work"
  weight = 3
  [[main.params]]
    icon = "fa-question"

[[main]]
name = "Technical Tools"
weight = 3
hasChildren = true
  [[main]]
  parent = "Technical Tools"
  name = "Bias detection tool"
  url = "/technical-tools/BDT"
  weight = 1
  [[main.params]]
    icon = "fa-search"
    subtitle = "Open source AI auditing tools"
  [[main]]
  parent = "Technical Tools"
  name = "Synthetic data generation"
  url = "/technical-tools/SDG"
  weight = 2
  [[main.params]]
    icon = "fa-table"
  [[main]]
  parent = "Technical Tools"
  name = "Github code"
  url = "https://github.com/NGO-Algorithm-Audit/"
  weight = 3
  [[main.params]]
    subtitle = "Code repository"
    icon = "fa-code"

[[main]]
name = "Knowledge platform"
weight = 4
hasChildren = true
  [[main]]
  parent = "Knowledge platform"
  name = "AI Act standards"
  url = "/knowledge-platform/standards"
  weight = 1
  [[main.params]]
    icon = "fa-check"
  [[main]]
  parent = "Knowledge platform"
  name = "AI policy observatory"
  url = "/knowledge-platform/policy-observatory"
  weight = 2
  [[main.params]]
    icon = "fa-binoculars"
  [[main]]
  parent = "Knowledge platform"
  name = "Knowledge base"
  url = "/knowledge-base"
  weight = 3
  [[main.params]]
    icon = "fa-brain"
  [[main]]
  parent = "Knowledge platform"
  name = "Services"
  url = "/services"
  weight = 4
  [[main.params]]
    icon = "fa-hands-helping"

[[main]]
name = "Events"
url = "events"
weight = 5
hasChildren = true
  [[main]]
  parent = "Events"
  name = "Activities"
  url = "/activities"
  weight = 1
  [[main.params]]
    icon = "fa-calendar"
  [[main]]
  parent = "Events"
  name = "Pressroom"
  url = "/pressroom"
  weight = 2
  [[main.params]]
    icon = "fa-newspaper"

[[main]]
name = "About"
weight = 6
hasChildren = true
  [[main]]
  parent = "About"
  name = "FAQ"
  url = "/faq"
  weight = 1
  [[main.params]]
    icon = "fa-question"
  [[main]]
  parent = "About"
  name = "Teams"
  url = "/teams"
  weight = 2
  [[main.params]]
    icon = "fa-users"
  [[main]]
  parent = "About"
  name = "Boards"
  url = "/boards"
  weight = 3
  [[main.params]]
    icon = "fa-user-friends"
  [[main]]
  parent = "About"
  name = "Vacancies"
  url = "/vacancies"
  weight = 4
  [[main.params]]
    icon = "fa-user-check"