# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "How we work"
url = "work"
weight = 2

[[main]]
name = "Cases"
url = "cases"
weight = 3

[[main]]
name = "Reading list"
url = "readings"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

[[main]]
name = "About"
url = "faq"
weight = 6