# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Cases"
url = "cases"
weight = 2

[[main]]
name = "Knowledge base"
url = "knowledge_base"
weight = 3

[[main]]
name = "FAQ"
url = "faq"
weight = 4

[[main]]
name = "About"
url = "about"
weight = 5