#################### default parameters ################################
logo = "images/logo.svg"
logo_width = "150px"
# OpenGraph / Twitter Card metadata
description = "Case-based knowledge for ethical algorithms"
author = "JFParie"
favicon = "/images/favicon.ico"
image = "images/logo2.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formspree.io/f/mrgrwnyo" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "LinkedIn"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/algorithm-audit/"

[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/NGO-Algorithm-Audit"